### ISSUE TITLE
What is it?

### ISSUE THREAD

**Issue by antofthy** [arjenlentz/routerfoo#1]
IT would be nice in the top level readme.md actually says what the project is for rather than just 

**First shown (in public) at Linux.conf.au 2021's SysAdmin miniconf**

Which explains nothing if you were not at that conference!

**Comment by arjenlentz** [comment]
There are snippets of config and script for routers/hosts, specifically on Linux... that'll apply in any situation as the subdirs/files indicate. For instance iptables = firewall. Do you feel that requires more context clarification?

The talk was as described in abstract.md
The fact that I built these things in a particular router is kinda a sideline - the lessons can be applied anywhere. The hardware is referenced as well though, for people who are interested in that.

Anyway, I'm happy to clarify or improve specific docs, but I'm not certain what you're unclear about.

**Comment by arjenlentz** [comment]
Added ref to abstract.md to README.md

**Comment by antofthy** [comment]
The point is someone coming along, for the first time will see the README.md.  This should first an immediately say, what this module in summery, after that it can point to more detail or other information.

I have seen this so many times it gets very annoying fast.  The author knows what it is, but someone else hitting the page for the first time does not.   The first thing that someone will want to know is "if this could be useful to us", so if it isn't they can move on.  They don't want to download, or search for a manual, or and abstract. They just want a quick 'What is it'.

This is what the synopsis on scientific papers formally do, right at the start, for the same reason.

So while a link is better.  A quick summery in the README.md file, just as you give in your reply to me, would be better still!

**Comment by arjenlentz** [comment]
Thank you kindly for your feedback, @antofthy
